### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by trueproof** [mafintosh/mkdirp-classic#1]
hi, i just noticed this module replaced original mkdirp in browserify, also found mkdirp 1.x by isaacs. While isaacs preserves substack's credits in https://github.com/isaacs/node-mkdirp/blob/master/LICENSE even after significant changes made, this simple fork is completely unattached from original author and even license doesn't mention him.

I 'm not exactly sure if it's ok, but i have a feeling like a giant is fading out, while some ppl (not about you) hide from others on which shoulders they stand mimicking his work.

**Comment by mafintosh** [comment]
Ah, I just have a repo generator that auto puts in my license. Let me link back to @substack's license as well.

**Comment by mafintosh** [comment]
done! thanks for bringing that to my attention
